---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.0

suites:
  - name: source
    run_list:
      - recipe[tdi-example-vim::default]
    attributes:
      vim:
        install_method: "source"
  - name: package
    run_list:
      - recipe[tdi-example-vim::default]
    attributes:
      vim:
        install_method: "package"
